# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'Beko' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'	

  # Pods for Beko
	
  target 'BekoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BekoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
